acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: acend
      replicaCount: 2
      image:
        repository: quay.io/acend/helm-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        secretOverride: acend-wildcard
        appname: helm-basics
        domain: training.acend.ch
    - 
      name: mobi
      replicaCount: 2
      image:
        repository: quay.io/acend/helm-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-mobi"
      ingress:
        secretOverride: acend-wildcard
        appname: helm-basics-mobi
        domain: training.puzzle.ch
    -
      name: openshift
      replicaCount: 2
      image:
        repository: quay.io/acend/helm-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-openshift"
      ingress:
        secretOverride: acend-wildcard
        appname: helm-basics-openshift
        domain: training.acend.ch



nameOverride: "acend-helm-basics"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
