theme = ["docsy-puzzle", "docsy-plus", "docsy"]

[params]
enabledModule = "base mobi rancher"
copyright = "Puzzle ITC GmbH"
imagePrefix = "puzzle_"

[[Languages.en.menu.main]]
copyright = "Puzzle ITC GmbH"
url = "https://www.puzzle.ch"

[params.replaceContent]
allowedHrefHosts = ['localhost', 'puzzle.ch', 'acend.ch']

[[params.replaceContent.placeholders]]
placeholder = "<registry-url>"
queryParam = "r"
defaultValue = "<registry-url>"

[[params.replaceContent.placeholders]]
placeholder = "<proxy>:<port>"
queryParam = "p"
defaultValue = "<proxy>:<port>"

[[params.replaceContent.placeholders]]
placeholder = "<noproxy-list>"
queryParam = "n"
defaultValue = "<noproxy-list>"

[[params.replaceContent.placeholders]]
placeholder = "<appdomain>"
queryParam = "a"
defaultValue = "<appdomain>"

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/acend/helm-basics-training"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/puzzleitc"

[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/puzzle-itc/"
