name: Build Training

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "content *.md"
          config_file: ".markdownlint.json"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      -
        name: Build Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/acend/helm-basics-training:pr-${{ github.event.pull_request.number }}
      -
        name: Build Mobi Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ACEND_HUGO_ENV=mobi
          push: true
          tags: |
            quay.io/acend/helm-basics-training:pr-${{ github.event.pull_request.number }}-mobi
      -
        name: Build Puzzle Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ACEND_HUGO_ENV=puzzle
          push: true
          tags: |
            quay.io/acend/helm-basics-training:pr-${{ github.event.pull_request.number }}-puzzle
      -
        name: Build Rancher Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ACEND_HUGO_ENV=rancher
          push: true
          tags: |
            quay.io/acend/helm-basics-training:pr-${{ github.event.pull_request.number }}-rancher
      -
        name: 'Deploy Helm Release'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'pr-${{ github.event.pull_request.number }}'
          namespace: 'acend-helm-basics-training-test'
          version: '${{ github.sha }}'
          repository: 'https://acend.github.io/helm-charts/'
          chart: 'acend-training-chart'
          token: '${{ github.token }}'
          helm: 'helm3'
          value-files: |
            [
              "helm-chart/values.yaml"
            ]

        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_TEST }}'
      -
        name: Redeploy acend Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-acend-helm-basics-acend --namespace acend-helm-basics-training-test
      -
        name: Redeploy mobi Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-acend-helm-basics-mobi --namespace acend-helm-basics-training-test
      -
        name: Redeploy Puzzle Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-acend-helm-basics-puzzle --namespace acend-helm-basics-training-test
      -
        name: Redeploy rancher Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-acend-helm-basics-rancher --namespace acend-helm-basics-training-test
      -
        name: Comment PR Environments in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
           PR Environments: 
           * acend version <https://helm-basics-pr-${{ github.event.pull_request.number }}.training.acend.ch>
           * mobi version <https://helm-basics-mobi-pr-${{ github.event.pull_request.number }}.k8s.puzzle.ch>
           * puzzle version <https://helm-basics-puzzle-pr-${{ github.event.pull_request.number }}.k8s.puzzle.ch>
           * rancher version <https://helm-basics-rancher-pr-${{ github.event.pull_request.number }}.training.acend.ch>
